### ISSUE TITLE
I use air sdk 18

### ISSUE THREAD

**Issue by imguenhoo** [Fabrice-Montfort/ezSpeech_ANE#3]
hello i have boungt your ane 

i try publish this app

but I can not do that 

because namespace invalidiate 22sdk

how can i use this ane at the another version

**Comment by Fabrice-Montfort** [comment]
Hi,

ezSpeech ANE is compiled with AIR 22.0. At this time, this is the minimum required version.

If you can, I really encourage you to upgrade your AIR version.

If not, I'll have to recompile ezSpeech with AIR 18.0 and make some tests.

I'll send you a copy via email to let you tests it with your project.

**Comment by imguenhoo** [comment]
hello 

um i try 23version but i can not use this ㅜㅜ ane

so current verision is air22 

um i used to another tts ane but this do not require sdk verision

can i get like that

**Comment by Fabrice-Montfort** [comment]
It works very well with AIR 23.0 (I use this configuration for my test project).

I'm downloading AIR 18.0 to recompile the ANE and send you a copy tomorrow if everything works as expected.

**Comment by imguenhoo** [comment]
thank you I will try 23sdk verison again

**Comment by Fabrice-Montfort** [comment]
I've tried to send you an email, but it seems that the one registred on my website is not valid.

Can you send me an email at hello@fabricemontfort.com

I've made some tests, and it works with AIR 18.0

I'll send you a copy when got a valid email.

Regards,
