### ISSUE TITLE
Chinese is doesn't work

### ISSUE THREAD

**Issue by smartfox** [Fabrice-Montfort/ezSpeech_ANE#5]
hello,
i testing the demo 
this.tts.setLanguage(languages.ZH);
if (this.tts.isSupported()){
	this.tts.say("你好。这是一个示例应用程序来演示说话的能力");
}
but it doesn't work
No sound was heard

Others，for example
languages.FR，languages.IT， languages.ES
all work fine

can i get some help?
My English is poor, can you understand it?

**Comment by Fabrice-Montfort** [comment]
Hi Smartfox,

I need more informations to reproduce your issue.

Can you tell me what AIR version, Phone model and OS version you are using ?

You can mail me on "hello at fabricemontfort dot com" if you want to send me project files. I will try to help you with ezSpeech ANE.

Thanks.

**Comment by smartfox** [comment]
Thank you for your help

On Android, if a specific TTS voice file is not installed and internet connection is available, ezSpeech ANE will download and install it automatically.
On iOS, all voices supported by this extension are pre-installed

Maybe that's the problem
On iOS，it run well,
But on Android, it doesn't work
In China, these files may not be downloaded

**Comment by Fabrice-Montfort** [comment]
Hi Smartfox,

I didn't encounter this issue (but I'm not in China). It's a little bit crazy that you can not make your Android device speaking chinese in China.

Do you have a specific TTS engine on your phone (in the settings of your Android device) ?

When you use Google Translate (for example). Does it speak chinese ?

Thanks for your answers.
