### ISSUE TITLE
Problème avec ezspeech demo

### ISSUE THREAD

**Issue by informeduc** [Fabrice-Montfort/ezSpeech_ANE#8]
Bonjour,
J'ai téléchargé la version démo afin de la tester avant achat de la version définitive.
Au lancement de l'application de test j'obtiens le message d'erreur que vous trouverez dans la capture d'écran jointe.
Ci-dessous l'entête du fichier -app.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<application xmlns="http://ns.adobe.com/air/application/30.0">

Pouvez-vous S?V?P? M'aider à résoudre ce problème.
Merci d'avance.
![ezspeech](https://user-images.githubusercontent.com/43416060/45765221-cd17a400-bc34-11e8-9948-2d753954a074.jpg)

Cordialement.

**Comment by informeduc** [comment]
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<application xmlns="http://ns.adobe.com/air/application/30.0">

**Comment by informeduc** [comment]
Je n'arrive pas à inclure l'entête du fichier -app.xml.
J'essaie encore
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<application xmlns="http://ns.adobe.com/air/application/30.0">

**Comment by informeduc** [comment]
"<?xml version="1.0" encoding="utf-8" standalone="no"?>
<application xmlns="http://ns.adobe.com/air/application/30.0">"

**Comment by informeduc** [comment]
Mon compilateur Flex tourne sur le sdk AIR 30.0

**Comment by informeduc** [comment]
Bonjour,
Je viens de commander la version payante de ezSpeech (order #387) et je rencontre toujours le même problème qu'avec la version démo que je vous ai signalé ci-dessus.
Je suis très surpris de n'avoir reçu aucune réponse de votre part.
Je vous mets donc en demeure de me fournir dans les plus brefs délais une solution pour que votre ANE fonctionne ou de me rembourser.
Avec mes remerciements anticipés
Cordialement.

Bruno CAULAVIER
S.A.R.L. SP LOG

**Comment by Fabrice-Montfort** [comment]
Je vais mettre à jour la version de la librairie vers AIR 30.

Par contre, il est bien entendu que ezSpeech est uniquement compatible avec les mobiles (Android et iOS) comme indiqué sur le site et dans la documentation.

Il me semble, de ce que je comprends de la ligne de commande et du message d'erreur montré dans votre ticket, que vous essayez de compiler pour Windows (ou peut être pour un émulateur).

La mise à jour sera disponible en tout début de semaine prochaine.

**Comment by informeduc** [comment]
Bonsoir,

Merci d’avoir essayé de me joindre par téléphone.
Sur mon compte PayPal, le remboursement et la restitution des fonds n’apparaissent pas, mais cela ne me gêne pas dans la mesure où nous réglons mon problème et que je puisse utiliser l’ANE.
Dans ce cas, et si effectivement le remboursement est effectif, je m’engage à renouveler la commande.
Effectivement, j’essaie de tester votre app nommée « Main » sur l’émulateur fourni avec FlashBuilder.
Si j’ai bien compris, je dois en fait générer un apk ou un ipa et le faire tourner directement sur un périphérique Android ou iOS. Est-ce bien cela ?

J’attends donc votre mise à jour car ezSpeech est important pour moi et pour les applications d’aide à la communication pour personnes handicapées que je développe.

Merci encore pour l’aide que vous pourrez m’apporter.

Bien cordialement.

B. CAULAVIER

De : Fabrice Montfort [mailto:notifications@github.com]
Envoyé : vendredi 5 octobre 2018 15:34
À : Fabrice-Montfort/ezSpeech_ANE
Cc : info@informatique-education.fr; Author
Objet : Re: [Fabrice-Montfort/ezSpeech_ANE] Problème avec ezspeech demo (#8)


Je vais mettre à jour la version de la librairie vers AIR 30.

Par contre, il est bien entendu que ezSpeech est uniquement compatible avec les mobiles (Android et iOS) comme indiqué sur le site et dans la documentation.

Il me semble, de ce que je comprends de la ligne de commande et du message d'erreur montré dans votre ticket, que vous essayez de compiler pour Windows (ou peut être pour un émulateur).

La mise à jour sera disponible en tout début de semaine prochaine.

**Comment by informeduc** [comment]
Bonsoir,

J’ai essayé à tout hasard de générer un apk et j’obtiens le message d’erreur ci-après que je vous communique en P.J. afin que vous ayez une information plus complète sur ce qui se passe.

Cordialement.

B. CAULAVIER

De : Fabrice Montfort [mailto:notifications@github.com]
Envoyé : vendredi 5 octobre 2018 15:34
À : Fabrice-Montfort/ezSpeech_ANE
Cc : info@informatique-education.fr; Author
Objet : Re: [Fabrice-Montfort/ezSpeech_ANE] Problème avec ezspeech demo (#8)


Je vais mettre à jour la version de la librairie vers AIR 30.

Par contre, il est bien entendu que ezSpeech est uniquement compatible avec les mobiles (Android et iOS) comme indiqué sur le site et dans la documentation.

Il me semble, de ce que je comprends de la ligne de commande et du message d'erreur montré dans votre ticket, que vous essayez de compiler pour Windows (ou peut être pour un émulateur).

La mise à jour sera disponible en tout début de semaine prochaine.

**Comment by Fabrice-Montfort** [comment]
Merci pour votre email m'indiquant que tout fonctionne comme décrit dans les documentations et sur mon site web.

ezSpeech utilise des fonctions natives du système, il ne fonctionne donc que sur des périphériques réels et pas dans les émulateurs.

Je clôture donc cette issue et vous souhaite le meilleur dans vos projets de développements AS3/AIR.
